### ISSUE TITLE
blog fork 가능할까요?

### ISSUE THREAD

**Issue by rimiiii** [sallyworld/blog#4]
안녕하세요!
이전에 포트폴리오 fork 문의드렸었는데 블로그 fork가 가능할까해서요!
이전에 블로그 정리하신거 봤었는데 지금은 다 사라졌네요ㅠㅠ
그때 UI가 마음에 들었는데 아예 닫으신걸까요??ㅠㅠ
혹시 그런게 아니라면 blog 출처를 밝히고 사용해보고 싶습니다!

**Comment by sallyworld** [comment]
관심 감사합니다. 빠른 시일 내로 복구하겠습니다. 😭

**Comment by rimiiii** [comment]
빠른 답변 감사합니다 ㅎㅎㅎㅎ
